stages:
  - build

variables:
  REVISION: "latest"

build_image:
  stage: build
  image: docker:git
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.e.foundation:5000
    - docker build -t registry.gitlab.e.foundation:5000/e/os/docker-lineage-cicd .
    - docker push registry.gitlab.e.foundation:5000/e/os/docker-lineage-cicd:$REVISION
  only:
    - /^master$/
    - web
